schema:
  - 'http://localhost:9000/'
documents:
  - 'src/**/*.graphql'
generates:
  src/utils/__generated__/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withRefetchFn: true
